apiVersion: v1
kind: ReplicationController
metadata:
  name: livefire-demo-rc
  labels:
    app: livefire-demo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: livefire-demo
    spec:
      containers:
      - name: livefire-demo
        image: livefire-pod:v3
        ports:
        - containerPort: 80
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
